### ISSUE TITLE
Debugging Scaled

### ISSUE THREAD

**Issue by dmg46664** [scaled/scaled#14]
Not an issue, but a documentation request.

It would be useful if steps could be provided in terms of how to setup debugging scaled.

My attempt was to import `/Users/username/Library/Application Support/Scaled/Packages/` into IntelliJ and try and get Pacman setup in order to run. However IntelliJ doesn't appear to be happy with the source and test structure by default complaining about various source files in the various subdirectories (probably because I haven't comprehensively linked everything up and every dependency... which seems like a large task to do manually). I imagine this is complicated because Scaled uses its own build system not intended for this purpose.

It would none-the-less be useful to know how to debug Scaled, to get to grips with the internals. This would allow me to solve my own problems such as:
https://github.com/dmg46664/jira-scaled-mode/issues/1

Thanks, much obliged :-)

**Comment by samskivert** [comment]
I don't have great advice for you here. Due to a potentially questionable desire on my part for Scaled packages to be loadable and unloadable at runtime (something I never actually wired up), Scaled splits most of its code across a whole bunch of package projects and each of those gets its own hierarchical tree of classloaders, based on the package's dependencies. This makes things messy from the standpoint of getting another IDE to understand Scaled code.

I had the idea at some point to make a "just jam it all into one giant classpath" mode that could be used when running Scaled in a debugger, but never sorted that out. As I've mentioned elsewhere, I usually debug Scaled by running with JRebel, hot reloading classes, and using printf where needed. Not the most sophisticated solution.

What might end up being slightly easier would be to have an option for Pacman to generate source jar files to go with the module.jar files that it already creates and then maybe an IDE could be fooled into treating the giant collection of module.jar and module-source.jar files as some sort of pre-built application that it then vaguely understood. Sort of how an IDE presumably groks a jar and source jar combo that it might find in a Maven repository. I can't volunteer to do that, but if you look at the Pacman code, it shouldn't be too onerous. Pacman already enumerates all the source files, compiles them and sticks the results in a jar file. Adding a flag to build (and rebuild) to also create source jars shouldn't mostly be a matter of making use of existing machinery.

**Comment by dmg46664** [comment]
Thanks for the explanation :-)

I am also partial to your "questionable desire... for Scaled packages to be loadable and unloadable at runtime". I have will see how I get on. Closing as it is merely a nice to have.
