### ISSUE TITLE
Meta key is not mapped to Alt on Ubuntu 14.04 

### ISSUE THREAD

**Issue by langley** [scaled/scaled#6]
Emacs is does this: if I hold down the Alt key and then hit x and emacs will show me M-x in the mini-buffer. But in scaled, I don't see anything and if I try to do M-v (which is the Alt key and v key) Scaled complains that 'v is undefined'.

**Comment by samskivert** [comment]
I don't have a hardware Linux machine to test on (though I'll try to remedy that soon). When I run Scaled in VirtualBox (hosted on Mac OS, target Ubuntu), it seems to do the right thing, but that's probably because my Mac has key mappings that are taking effect.

If Scaled is saying "v is undefined" that's weird. Because plain old 'v' should be defined, but if it has a modifier key, that should get mapped back to a key string like M-v or A-v, so it should say "A-v is undefined".

I'll see what I can figure out. I also have a keymap testing program that I wrote to report some bugs for JavaFX, so maybe you can run that and tell me what it prints when you press M-v and A-v:

```
import java.util.Arrays;
import java.util.Set;
import java.util.HashSet;
import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.input.KeyEvent;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class MetaDot extends Application {
  public static void main(String[] args) {
    launch(args);
  }

  @Override
  public void start(Stage primaryStage) {
    primaryStage.setTitle("Meta Dot!");
    StackPane root = new StackPane();
    root.getChildren().add(new Label("Press Meta Dot."));
    primaryStage.addEventHandler(KeyEvent.ANY, ev -> System.out.println(toDebugString(ev)));
    primaryStage.setScene(new Scene(root, 300, 250));
    primaryStage.show();
  }

  private String toDebugString (KeyEvent ev) {
    StringBuilder sb = new StringBuilder();
    sb.append("type=").append(ev.getEventType());
    sb.append(" code=").append(ev.getCode());
    sb.append(" mods=").append(getModifiers(ev));
    sb.append(" char='").append(ev.getCharacter());
    sb.append("' (");
    for (char c : ev.getCharacter().toCharArray()) sb.append(" ").append((int)c);
    sb.append(")");
    return sb.toString();
  }

  private Set<String> getModifiers (KeyEvent ev) {
    Set<String> set = new HashSet<>();
    if (ev.isAltDown()) set.add("alt");
    if (ev.isControlDown()) set.add("ctrl");
    if (ev.isMetaDown()) set.add("meta");
    if (ev.isShiftDown()) set.add("shift");
    return set;
  }
}
```

**Comment by samskivert** [comment]
OK weird. I apparently haven't run in Ubuntu in a while. Good lord they hijack the Meta key and do all sorts of terrible things with it. I guess that's not so bad when you use Alt as Meta and thus never press Meta. On my Mac I have Alt and Meta swapped because I'm using a PC keyboard on my Mac which puts the Alt key where the (Mac) Meta key would be. Anyway.

Scaled isn't doing the right thing with Alt on VirtualBox either, which is good because I should be able to debug it! I'll dig in a big and you'll either see a patch shortly or another message here with bad news. :)

**Comment by samskivert** [comment]
OK, I guess I was just being dense. On Linux, Emacs maps Alt to Meta, and Windows to Super. I'm mapping Alt to Alt and Windows to Meta. I just need to map Alt to Meta and probably Windows to Alt (since Alt isn't really used much by Emacs, like Super), and everything will probably be fine.

I'll hack something in there, and then reconsider whether something more general purpose would be useful.

**Comment by samskivert** [comment]
OK, I committed a hacky fix. Let me know if you still have issues. I'll potentially revisit this if a more general modifier key remapping scheme turns out to be needed, but I think I've addressed the basic confusion, which is that JavaFX maps Alt to Alt and Windows to Meta, whereas Emacs maps Alt to Meta and Windows to Super.

**Comment by langley** [comment]
I'll try it out today. THANKS for looking into this.
On Ubuntu 14.04, the Unity windows manager comes with a number of
"accelerators"/"launchers" that trigger off of keybindings. I disabled a
number of these, originally thinking the window manager was hijacking the
keys; but your explorations prove that wasn't the problem.

You can disable these keybindings with the System Settings widget and then
it is  -> keyboard -> Launchers. Also I used  compizconfig-settings-manager
(which I had to do a sudo apt-get install to get; it's launched with the
cli command 'ccsm') to disable more. I only mention all this by way of
history for other Ubuntu and Unity people.

Thanks; looking forward to trying the keymap tester and the change.
